[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true

[images]
  remote_images = ["https://source\\.unsplash\\.com/.*", "https://images\\.unsplash\\.com/.*", "https://ext\\.same-assets\\.com/.*", "https://ugc\\.same-assets\\.com/.*"]
